# -*- coding: utf-8 -*-
"""ytcom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB888mdlD7dR7pRaWlNPCc8G6R2jMe_X
"""

from googleapiclient.discovery import build

def get_youtube_comments(api_key, video_id, max_results=500):
    youtube = build("youtube", "v3", developerKey=api_key)
    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        maxResults=max_results
    )
    response = request.execute()

    comments = [item["snippet"]["topLevelComment"]["snippet"]["textOriginal"] for item in response["items"]]
    return comments